#! /usr/bin/bash
mpiexec -np 2 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 512 input8GB.fastq testing_out.ngsc
mpiexec -np 2 ./main -c 1024 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 512 input8GB.fastq testing_out.ngsc
mpiexec -np 4 ./main -c 1024 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 512 input8GB.fastq testing_out.ngsc
mpiexec -np 8 ./main -c 1024 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 512 input8GB.fastq testing_out.ngsc
mpiexec -np 16 ./main -c 1024 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 512 input8GB.fastq testing_out.ngsc
mpiexec -np 32 ./main -c 1024 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 64 ./main -c 512 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 128 ./main -c 256 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 64 input8GB.fastq testing_out.ngsc
mpiexec -np 256 ./main -c 128 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 1 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 2 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 4 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 8 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 16 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 32 input8GB.fastq testing_out.ngsc
mpiexec -np 512 ./main -c 64 input8GB.fastq testing_out.ngsc
