#! /usr/bin/bash
mpiexec -np 2 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 512 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 1024 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 512 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 1024 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 512 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 1024 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 512 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 1024 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 512 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 1024 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 512 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 256 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 128 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 1 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 2 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 4 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 8 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 16 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 32 comp8GB.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 64 comp8GB.ngsc decomp_testing_out.fastq
