#! /usr/bin/bash
mpiexec -np 2 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 512 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 2 ./main -d 1024 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 512 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 4 ./main -d 1024 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 512 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 8 ./main -d 1024 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 512 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 16 ./main -d 1024 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 512 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 32 ./main -d 1024 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 64 ./main -d 512 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 128 ./main -d 256 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 256 ./main -d 128 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 1 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 2 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 4 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 8 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 16 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 32 testing_out.ngsc decomp_testing_out.fastq
mpiexec -np 512 ./main -d 64 testing_out.ngsc decomp_testing_out.fastq
