#! /usr/bin/bash
mpiexec -np 2 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 512 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 2 ./main -i 1024 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 512 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 4 ./main -i 1024 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 512 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 8 ./main -i 1024 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 512 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 16 ./main -i 1024 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 512 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 32 ./main -i 1024 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 64 ./main -i 512 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 128 ./main -i 256 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 256 ./main -i 128 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 1 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 2 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 4 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 8 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 16 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 32 comp8GB.ngsc fasta_testing_out.fasta -fasta
mpiexec -np 512 ./main -i 64 comp8GB.ngsc fasta_testing_out.fasta -fasta
