#! /usr/bin/bash
mpiexec -np 2 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 512 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 512 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 512 testing_out.ngsc -findall GGCGC
mpiexec -np 2 ./main -i 1024 testing_out.ngsc -findall TATA
mpiexec -np 2 ./main -i 1024 testing_out.ngsc -findall CCAAT
mpiexec -np 2 ./main -i 1024 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 512 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 512 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 512 testing_out.ngsc -findall GGCGC
mpiexec -np 4 ./main -i 1024 testing_out.ngsc -findall TATA
mpiexec -np 4 ./main -i 1024 testing_out.ngsc -findall CCAAT
mpiexec -np 4 ./main -i 1024 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 512 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 512 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 512 testing_out.ngsc -findall GGCGC
mpiexec -np 8 ./main -i 1024 testing_out.ngsc -findall TATA
mpiexec -np 8 ./main -i 1024 testing_out.ngsc -findall CCAAT
mpiexec -np 8 ./main -i 1024 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 512 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 512 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 512 testing_out.ngsc -findall GGCGC
mpiexec -np 16 ./main -i 1024 testing_out.ngsc -findall TATA
mpiexec -np 16 ./main -i 1024 testing_out.ngsc -findall CCAAT
mpiexec -np 16 ./main -i 1024 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 512 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 512 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 512 testing_out.ngsc -findall GGCGC
mpiexec -np 32 ./main -i 1024 testing_out.ngsc -findall TATA
mpiexec -np 32 ./main -i 1024 testing_out.ngsc -findall CCAAT
mpiexec -np 32 ./main -i 1024 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 64 ./main -i 512 testing_out.ngsc -findall TATA
mpiexec -np 64 ./main -i 512 testing_out.ngsc -findall CCAAT
mpiexec -np 64 ./main -i 512 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 128 ./main -i 256 testing_out.ngsc -findall TATA
mpiexec -np 128 ./main -i 256 testing_out.ngsc -findall CCAAT
mpiexec -np 128 ./main -i 256 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 64 testing_out.ngsc -findall GGCGC
mpiexec -np 256 ./main -i 128 testing_out.ngsc -findall TATA
mpiexec -np 256 ./main -i 128 testing_out.ngsc -findall CCAAT
mpiexec -np 256 ./main -i 128 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 1 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 1 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 1 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 2 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 2 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 2 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 4 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 4 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 4 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 8 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 8 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 8 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 16 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 16 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 16 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 32 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 32 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 32 testing_out.ngsc -findall GGCGC
mpiexec -np 512 ./main -i 64 testing_out.ngsc -findall TATA
mpiexec -np 512 ./main -i 64 testing_out.ngsc -findall CCAAT
mpiexec -np 512 ./main -i 64 testing_out.ngsc -findall GGCGC
